{{- if eq .Values.redis.enabled true -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    template: redis-persistent-template  
  name: {{ template "redis.name" . }}
stringData:
  database-password: {{ .Values.redis.redis_password }}
{{- end }}